"""index case lookups and pending effects

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 01:15:16.704162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deliveries_received_at'), 'deliveries', ['received_at'], unique=False)
    op.create_index(op.f('ix_effects_case_id'), 'effects', ['case_id'], unique=False)
    op.create_index(op.f('ix_effects_status'), 'effects', ['status'], unique=False)
    op.create_index(op.f('ix_runs_case_id'), 'runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_transitions_case_id'), 'transitions', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transitions_case_id'), table_name='transitions')
    op.drop_index(op.f('ix_runs_case_id'), table_name='runs')
    op.drop_index(op.f('ix_effects_status'), table_name='effects')
    op.drop_index(op.f('ix_effects_case_id'), table_name='effects')
    op.drop_index(op.f('ix_deliveries_received_at'), table_name='deliveries')
    # ### end Alembic commands ###
