"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 01:14:44.265257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=True),
    sa.Column('auto_labels', sa.JSON(), nullable=True),
    sa.Column('repro_package', sa.String(length=255), nullable=True),
    sa.Column('repro_import_name', sa.String(length=255), nullable=True),
    sa.Column('repro_source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'full_name')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('author_login', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('spent_usd', sa.Float(), nullable=False),
    sa.Column('summary_comment_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'kind', 'number')
    )
    op.create_table('doc_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('heading', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_chunks_repo_id'), 'doc_chunks', ['repo_id'], unique=False)
    op.create_table('issue_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_reason', sa.String(length=32), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('trace_sig', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'number')
    )
    op.create_index(op.f('ix_issue_docs_repo_id'), 'issue_docs', ['repo_id'], unique=False)
    op.create_table('effects',
    sa.Column('effect_key', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('effect_key')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('acceptance', sa.Boolean(), nullable=False),
    sa.Column('test_path', sa.String(length=512), nullable=False),
    sa.Column('test_code', sa.Text(), nullable=False),
    sa.Column('test_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_repo', sa.String(length=255), nullable=True),
    sa.Column('source_sha', sa.String(length=64), nullable=True),
    sa.Column('python', sa.String(length=16), nullable=True),
    sa.Column('pytest', sa.String(length=64), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('fail_rate', sa.Float(), nullable=True),
    sa.Column('receipt', sa.JSON(), nullable=False),
    sa.Column('receipt_sha256', sa.String(length=64), nullable=False),
    sa.Column('superseded_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=32), nullable=False),
    sa.Column('skill_version', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('tokens_cached', sa.Integer(), nullable=False),
    sa.Column('usd', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('receipt', sa.JSON(), nullable=False),
    sa.Column('receipt_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_case_id'), 'verifications', ['case_id'], unique=False)
    op.create_table('hidden_exams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('test_path', sa.String(length=512), nullable=False),
    sa.Column('test_code', sa.Text(), nullable=False),
    sa.Column('test_sha256', sa.String(length=64), nullable=False),
    sa.Column('tests', sa.JSON(), nullable=False),
    sa.Column('receipt', sa.JSON(), nullable=False),
    sa.Column('receipt_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hidden_exams_evidence_id'), 'hidden_exams', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hidden_exams_evidence_id'), table_name='hidden_exams')
    op.drop_table('hidden_exams')
    op.drop_index(op.f('ix_verifications_case_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_table('transitions')
    op.drop_table('runs')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('effects')
    op.drop_index(op.f('ix_issue_docs_repo_id'), table_name='issue_docs')
    op.drop_table('issue_docs')
    op.drop_index(op.f('ix_doc_chunks_repo_id'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    op.drop_table('cases')
    op.drop_table('repos')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
